'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Java_IDE.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to import java.io.*;
        '''import java.lang.*;
        '''import java.util.*;
        '''import java.applet.*;
        '''import java.awt.*;
        '''import java.awt.event.*;
        '''
        '''/*
        '''&lt;applet code = &quot;Untitled&quot; width = &quot;500&quot; height = &quot;500&quot;&gt;&lt;/applet&gt;
        '''*/
        '''
        '''public class Untitled extends Applet
        '''{
        '''	public void init()
        '''	{
        '''		//initialization
        '''	}
        '''	
        '''	public void start ()
        '''	{
        '''		//start or resume execution
        '''	}
        '''	
        '''	public void stop()
        '''	{
        '''		//suspend execution
        '''	}
        '''	
        '''	public void destroy()
        '''	{
        '''		//perform shutdown activity
        '''	}
        '''	
        '''	public void paint (Graph [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Applet() As String
            Get
                Return ResourceManager.GetString("Applet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Banner() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Banner", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to import java.io.*;
        '''import java.lang.*;
        '''import java.util.*;
        '''
        '''public class Untitled
        '''{
        '''	public static void main (String args [])
        '''	{
        '''		System.out.println(&quot;Hello World!&quot;);
        '''	}
        '''}.
        '''</summary>
        Friend ReadOnly Property Java() As String
            Get
                Return ResourceManager.GetString("Java", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
